[colors.bright]
black = "#5e5c64"
blue = "#2a7bde"
cyan = "#33c7de"
green = "#33d17a"
magenta = "#c061cb"
red = "#f66151"
white = "#ffffff"
yellow = "#e9ad0c"

[colors.normal]
black = "#171421"
blue = "#12488b"
cyan = "#2aa1b3"
green = "#26a269"
magenta = "#a347ba"
red = "#c01c28"
white = "#d0cfcc"
yellow = "#a2734c"

[colors.primary]
background = "#171421"
bright_foreground = "#ffffff"
foreground = "#d0cfcc"

[font]
size = 11.0

[selection]
save_to_clipboard = true

[window.dimensions]
columns = 80
lines = 43

[window.padding]
x = 0
y = 0
