FROM quay.io/fedora/fedora-kinoite:41

RUN curl -fsSLO https://ollama.com/install.sh && chmod a+x install.sh && \
      sed -i "s/set -eu/set -eux/g" install.sh && \
      sed -i "s# in /usr/local/bin# in#g" install.sh && \
      ./install.sh
RUN dnf install -y alacritty black clang cmake codespell distrobox dnf4 \
      fedora-workstation-repositories gcc hyperfine keepassxc libcurl-devel \
      make nvtop podman python3-tqdm qemu-kvm the_silver_searcher vim \
      python3-flake8 bats httpd-tools docker
RUN dnf remove -y nano
RUN dnf update -y

