FROM quay.io/fedora/fedora-kinoite:42

RUN curl -fsSLO https://ollama.com/install.sh && chmod a+x install.sh && \
      sed -i "s/set -eu/set -eux/g" install.sh && \
      sed -i "s# in /usr/local/bin# in#g" install.sh && \
      ./install.sh
RUN curl -fsSL https://get.docker.com | bash
RUN dnf install -y alacritty black clang cmake codespell distrobox dnf4 \
      fedora-workstation-repositories gcc hyperfine keepassxc libcurl-devel \
      make nvtop python3-tqdm qemu-kvm the_silver_searcher vim python3-flake8 \
      bats httpd-tools ninja meson python3-jinja2 SDL2-devel crun-krun podman \ 
      docker-model-plugin
RUN dnf remove -y nano
RUN curl -fsSL -o /usr/bin/build_llama_and_whisper.sh https://raw.githubusercontent.com/containers/ramalama/6d7effadc2f6cd8bf7b231af965e367e65153029/container-images/scripts/build_llama_and_whisper.sh
RUN chmod a+rx /usr/bin/build_llama_and_whisper.sh && build_llama_and_whisper.sh "rocm"

