#!/bin/bash

set -e

NAME=$1
IMG=$2

USER=$(id -un)
GID=$(id -g)
GROUP=$(id -gn)

# --privileged needed for dmidecode
sudo podman run --privileged -t -d -v /tmp:/tmp -v "/home/$USER:/home/$USER" -h "$NAME" --name "$NAME" "$IMG" /bin/bash

podExe() {
  local cmd=$1

  sudo podman exec -t "$NAME" /bin/bash -c "$cmd"
}

podExe "groupadd -g $GID $GROUP && useradd -M -s /bin/bash -g $GID -u $UID $USER" &
podExe "printf '$USER ALL=(ALL) NOPASSWD: ALL\n' >> /etc/sudoers" &

