FROM ubuntu:24.04 AS base

WORKDIR /workspace/

RUN <<EOF
#!/bin/bash

main() {
  set -eux -o pipefail
  apt-get update -y
  apt-get install -y --no-install-recommends git curl wget ca-certificates \
    gcc g++ libtcmalloc-minimal4 libnuma-dev ffmpeg libsm6 libxext6 libgl1 jq \
    lsof vim
  curl -LsSf https://astral.sh/uv/0.7.21/install.sh | bash
  rm -rf /var/lib/apt/lists/*

  local arch=$(uname -m)
  echo -n "LD_PRELOAD=/usr/lib/$arch-linux-gnu/libtcmalloc_minimal.so.4" >> /etc/environment
  if [ "$arch" = "x86_64" ]; then
    echo -n ":/opt/venv/lib/libiomp5.so" >> /etc/environment
  fi

  echo >> /etc/environment
  echo 'ulimit -c 0' >> ~/.bashrc
}

main "$@"
EOF

ENV PATH="/root/.local/bin:$PATH"
ENV VIRTUAL_ENV="/opt/venv"
ENV UV_PYTHON_INSTALL_DIR=/opt/uv/python
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

ENV UV_HTTP_TIMEOUT=500

ENV PIP_EXTRA_INDEX_URL="https://download.pytorch.org/whl/cpu"
ENV UV_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}
ENV UV_INDEX_STRATEGY="unsafe-best-match"
ENV UV_LINK_MODE="copy"

ENV VLLM_CPU_DISABLE_AVX512=0
ENV VLLM_CPU_AVX512BF16=0
ENV VLLM_CPU_AVX512VNNI=0

RUN <<EOF
#!/bin/bash

main() {
  set -eux -o pipefail

  uv venv --python 3.12 --seed ${VIRTUAL_ENV}
  uv pip install --upgrade pip

  local v_vn="0.9.2"
  local vllm_url="https://github.com/vllm-project/vllm"
  curl -LsSf $vllm_url/releases/download/v$v_vn/vllm-$v_vn.tar.gz | tar xz
  cd vllm-$v_vn
  uv pip install -r requirements/cpu-build.txt
  VLLM_TARGET_DEVICE=cpu python3 setup.py bdist_wheel
  uv pip install dist/*.whl
  cd -
  rm -rf vllm-$v_vn .cache
}

main "$@"
EOF

