#!/bin/bash

set -eu

git add -u
git commit -a --amend --no-edit &
git fetch

if [ "$(git rev-parse --abbrev-ref HEAD)" == "master" ]; then
  git push
else
  git rebase origin/master
  git push --force-with-lease
fi

